import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { CustomFooter } from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { SubjectProvider } from "@/context/SubjectContext";
import Script from "next/script";

const workSans = localFont({
	src: [
		{
			path: "./fonts/WorkSans-Black.ttf",
			weight: "900",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-ExtraBold.ttf",
			weight: "800",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-ExtraLight.ttf",
			weight: "200",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-Medium.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-Regular.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-SemiBold.ttf",
			weight: "900",
			style: "normal",
		},
		{
			path: "./fonts/WorkSans-Thin.ttf",
			weight: "200",
			style: "normal",
		},
	],
	variable: "--font-work-sans",
});

export const metadata: Metadata = {
	title: "Hour Zero",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<Script
					src="https://www.google.com/recaptcha/api.js"
					strategy="beforeInteractive"
				/>
			</head>
			<body className={`${workSans.variable} bg-black`}>
				<SubjectProvider>
					<Navbar />
					{children}
					<Toaster />
					<CustomFooter />
				</SubjectProvider>
			</body>
		</html>
	);
}
